name: telegram messaging test
on: [push]
jobs:
    tg_msg_job:
        runs-on: ubuntu-latest
        name: A job to test this action
        steps:
            - name: Send Message
              id: test
              uses: Juuroku/telegram-messaging@v0.5
              with: 
                telegram-token:  ${{ secrets.TELEGRAM_TOKEN }}
                telegram-chat: ${{ secrets.TELEGRAM_ID }}
                message: |
                    *Message From Telegram Messaging Action*
                    Test Message
                parse: 'markdown'
            - name: Get the output
              run: echo "${{ steps.test.outputs.status }}"