name: telegram messaging test
on: [push]
jobs:
    tg_msg_job:
        runs-on: ubuntu-latest
        name: A job to test this action
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Send Message
              id: test
              uses: ./
              with: 
                telegram-token:  ${{ secrets.TELEGRAM_TOKEN }}
                telegram-chat: ${{ secrets.TELEGRAM_ID }}
                message: |
                    *[${{ github.repository }}](${{ github.repositoryUrl }}) Push Event*
                    REF: ${{ github.ref_name }}
                    [LATEST COMMIT](${{ github.event.head_commit.url }}): 
                        ${{ github.event.head_commit.message }}
                    
                parse: 'markdown'
            - name: Get the output
              run: echo "${{ steps.test.outputs.status }}"
    parse_check:
        runs-on: ubuntu-latest
        name: Check parse mode
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Send Message
              id: parse
              uses: ./
              with:
                telegram-token:  ${{ secrets.TELEGRAM_TOKEN }}
                telegram-chat: ${{ secrets.TELEGRAM_ID }}
                message: |
                    no parse
            - name: Get the output
              run: echo "${{ steps.test.outputs.status }}"
    